# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import lasana.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=lasana.models.MealStorage(), upload_to='/tmp/', verbose_name='File')),
                ('expiration_time', models.DateTimeField(db_index=True, verbose_name='Expiration time')),
            ],
            options={
                'ordering': ['expiration_time'],
                'verbose_name': 'Meal',
            },
        ),
    ]
